### ISSUE TITLE
Module not found: Error

### ISSUE THREAD

**Issue by tomhughesnice** [reapp/starter-default#5]
I followed the instructions listed at http://reapp.io/start.html#why-reapp?
`npm install -g reapp`
`reapp new demo`
`cd demo && reapp run`

Received the following error output.

Your app is running on http://localhost:3010

Building with Webpack...
Hash: e779570c713250e7b167
Version: webpack 1.12.14
Time: 622ms
  Asset     Size  Chunks       Chunk Names
main.js  22.3 kB       0       main
chunk    {0} main.js (main) 52 bytes [rendered]
    [0] multi main 52 bytes {0} [built] [3 errors]

**ERROR in multi main
Module not found: Error: Cannot resolve module 'webpack-dev-server/client' in /Users/thomashughes/Repositories/demo
 @ multi main**

**ERROR in multi main
Module not found: Error: Cannot resolve module 'webpack/hot/only-dev-server' in /Users/thomashughes/Repositories/demo
 @ multi main**

**ERROR in multi main
Module not found: Error: Cannot resolve module 'babel-loader' in /Users/thomashughes/Repositories/demo
 @ multi main**
webpack: bundle is now VALID.

Build took 0.622 seconds

Any help would be appreciated? I would like to try out this framework.
npm version 3.7.3
node version 5.8.0

**Comment by sigeje** [comment]
Hi @tomhughesnice ,
I have just tried on my laptop using the same version of npm and node as yours and it's working.
Have you installed react@0.13.2, reapp-ui@0.12.54, reapp-kit@1.2.15 in your application directory? As mentioned in this rev [reapp/reapp@d8fe0c8](https://github.com/reapp/reapp/commit/d8fe0c89bf28ab073a33320639574d074b621726)

Hope it helps

**Comment by tomhughesnice** [comment]
Hi @sigeje thanks for your help. I just tried what you suggested though and the same error still persists.

This is the demo on the front page of their website, doesn't specify installing any other dependancies I can see. Hopefully the maintainer of this repo will get back to me, as its quite an off putting start to using this framework.

**Comment by sigeje** [comment]
If I read the error messages, apparently some libraries were not found by the starter app. Those all are belong to reapp-pack which is the dependency of reapp. How about running `npm install` inside reapp-pack directory @tomhughesnice ?
reapp-pack should be exist in reapp/node_modules and reapp should be exist in npm global modules directory. So, try to cd to {global modules directory}/reapp/node_modules/reapp-pack then run the `npm install` command.

**Comment by tomhughesnice** [comment]
Hi,
I could not find the module reapp-pack inside my node_modules, so I just ran
`npm install reapp-pack` on project and retried running my app and now it is working as expected.

Thanks for your help, I can only assume an npm dependancy is setup incorrectly somewhere.

**Comment by sigeje** [comment]
Cool, happy coding @tomhughesnice !
